a: a

b:
  - 1
    2


networkConfig1:
  - field1: 1
    field2: 2
    field3: "ff"
  - field1: 1
    field2: 3
    field3: "ff"
    field4: true
    field5: "false"

networkConfig2:
  field1: 1
  field2: 3
  field3: "ff"
  field4: true
  field5: "false"
  fieldName: "阿拉大方拉风 asf"