a: a

b:
  - 1
    2


networkConfig1:
  - field1: 1
    field2: 2
    field3: "ff"
  - field1: 1
    field2: 3
    field3: "ff"
    field4: true
    field5: "false"

Access-Clients:
  app1:
    clientName: app1
    accessKeyID: 23e3
    secretAccessKey: awef
    enabled: true
    scope:
      - /index
      - /about
  app2:
    clientName: app2
    accessKeyID: 23e3
    secretAccessKey: awef
    enabled: true
    scope:
      - /index
      - /about