# 多数据源配置
MySQLDataSource:
  - MYSQL_NAME: zero4rs_db
    MYSQL_ENABLE: true
    MYSQL_SERVER: 127.0.0.1:3307
    MYSQL_DATABASE: zero4rs_db?timeout=90s&interpolateParams=true&multiStatements=true&charset=utf8&autocommit=true&parseTime=True&loc=Asia%2FShanghai
    MYSQL_USER_NAME: keesh
    MYSQL_PASSWD: Cc
    MYSQL_MAPPER_LOCATION: "./META-INF/mappers/zero4rs_db/*.txt"
  - MYSQL_NAME: ipro4rs_db
    MYSQL_ENABLE: true
    MYSQL_SERVER: 127.0.0.1:3307
    MYSQL_DATABASE: ipro4rs_db?timeout=90s&interpolateParams=true&multiStatements=true&charset=utf8&autocommit=true&parseTime=True&loc=Asia%2FShanghai
    MYSQL_USER_NAME: keesh
    MYSQL_PASSWD: Cc
    MYSQL_MAPPER_LOCATION: "./META-INF/mappers/ipro4rs_db/*.txt"

Access-Clients:
  app1:
    clientName: app1
    accessKeyID: 23e3
    secretAccessKey: awef
    enabled: true
    scope:
      - /index
      - /about
  app2:
    clientName: app2
    accessKeyID: 23e3
    secretAccessKey: awef
    enabled: true
    scope:
      - /index
      - /about